### ISSUE TITLE
Icons

### ISSUE THREAD

**Issue by tommrt** [tommrt/react-html-template-editor#11]
Need to decide / implement icons

**Comment by tommrt** [comment]
I think we create our own icon set (possibly its own package).

**Comment by tommrt** [comment]
example: a tick
```HTML
<svg id="svg" height="100" width="100" viewBox="0 0 24 24">
  <polyline 
            points="2 2 10 22 16 14" />
</svg>
```

```CSS
svg {
  stroke: currentColor;
  stroke-width: 2px;
  fill: none;
}
```

**Comment by tommrt** [comment]
resource
https://www.aleksandrhovhannisyan.com/blog/svg-tutorial-how-to-code-svg-icons-by-hand/

**Comment by tommrt** [comment]
### bad example: tick circle
```HTML
<svg id="svg" height="100" width="100" viewBox="0 0 24 24">
  <polyline 
            points="8 8 12 18 15 15" />
  <circle cx="12" cy="12" r="10"/>
</svg>
```
```CSS
svg {
  stroke: currentColor;
  stroke-width: 2px;
  fill: none;
  stroke-linejoin: round;
  stroke-linecap: round;
}
```
